{% set name = "tifffile" %}
{% set version = "2021.10.12" %}
{% set sha256 = "0a78268a2d844af94929512d28b39bd1ea6fe46de4124103840b5fe4e1c555cd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tifffile = tifffile:main
    - lsm2bin = tifffile.lsm2bin:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.15.1
    - imagecodecs >=2021.7.30

test:
  imports:
    - tifffile

about:
  home: https://github.com/cgohlke/tifffile
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files.

extra:
  recipe-maintainers:
    - blink1073
    - ericpre
    - jakirkham
    - mrakitin
    - ocefpaf
    - stuarteberg
